import type { Metadata } from "next";
import "./globals.css";
import MainHeader from "./components/header/Header";
import MainFooter from "./components/footer/Footer";
import { SectionProvider } from "./components/Custom/Hook/SectionContext";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Clothing Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <SectionProvider>
          <Suspense fallback={null}>
            <MainHeader />
          </Suspense>

          <div className="mt-24">
            {children}
          </div>

          <MainFooter />

        </SectionProvider>
      </body>
    </html>
  );
}
